# Generated by Django 4.2.7 on 2026-01-25 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('upload_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('avg_flowrate', models.FloatField()),
                ('avg_pressure', models.FloatField()),
                ('avg_temperature', models.FloatField()),
                ('equipment_type_distribution', models.JSONField()),
                ('total_records', models.IntegerField()),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
    ]
